{% set name = "r5py" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 26073a4556ae1542b9c3040b1f599807e760e7b664ee28d0e0a1a678330b0270

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - openjdk >=11
    - pip
  run:
    - python >=3.8
    - openjdk >=11
    - ConfigArgParse
    - geopandas
    - joblib
    - jpype1
    - numpy
    - pandas
    - psutil
    - requests

test:
  imports:
    - r5py

about:
  home: https://github.com/r5py/r5py
  summary: "Python wrapper for the R5 routing analysis engine"
  description: |
    R5py is a Python wrapper for the R5 routing analysis engine. It’s inspired by r5r, a wrapper for R, and is designed to interact with GeoPandas data frames.
    Similar to r5r, r5py represents a simple way to run R5 locally. It allows users to generate detailed routing analyses or calculate 
    travel time matrices using parallel computing, and integrates seamlessly with Python/Geopandas workflows.
  license: GPL-3.0-or-later OR MIT
  license_file:
    - LICENSE
    - licenses/
  doc_url: https://r5py.readthedocs.io/
  dev_url: https://github.com/r5py/r5py

extra:
  recipe-maintainers:
    - HTenkanen
    - christophfink
